version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Install phase started on `date`
      - echo Installing system dependencies...
      - apt-get update -qq
      - apt-get install -y -qq libsqlite3-dev sqlite3 build-essential
      - python -m pip install --upgrade pip

  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Verifying SQLite3 installation...
      - python -c "import sqlite3; print('SQLite3 version:', sqlite3.sqlite_version)"
      - echo Installing Python dependencies...
      - pip install -r requirements.txt
      - pip install -r requirements-test.txt
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 982590066015.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - python -m pytest tests/ -v --tb=short
      
      - echo Building Docker image...
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - docker build -t devops_python .
      
      - echo Saving Docker image as artifact...
      - docker save devops_python:latest -o devops_python-image.tar
      - gzip devops_python-image.tar
      - docker tag devops_python:latest 982590066015.dkr.ecr.us-east-2.amazonaws.com/devops_python:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating deployment package...
      - echo "IMAGE_TAG=$IMAGE_TAG" > deployment-info.txt
      - echo "BUILD_TIME=$(date)" >> deployment-info.txt
      - echo "COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}" >> deployment-info.txt
      - echo "DOCKER_IMAGE=devops_python:$IMAGE_TAG" >> deployment-info.txt
      - echo "DOCKER_IMAGE_LATEST=devops_python:latest" >> deployment-info.txt
      - docker push 982590066015.dkr.ecr.us-east-2.amazonaws.com/devops_python:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"982590066015.dkr.ecr.us-east-2.amazonaws.com/devops_python:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"982590066015.dkr.ecr.us-east-2.amazonaws.com/devops_python:latest"}' > imageDetail.json
      - cat imagedefinitions.json 

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - appspec.json
    - taskdef.json
    - docker-compose.yml
    - Dockerfile
    - scripts/**/*

cache:
  paths:
    - '/root/.cache/pip/**/*'
